version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: sample-python-flask-service/scripts/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: sample-python-flask-service/scripts/start_container.sh
      timeout: 300
      runas: root
